version: '3.8'

services:
  minio:
    image: minio/minio:RELEASE.2025-03-12T18-04-18Z-cpuv1
    ports:
      - "1237:9001"
      - "1238:9000"
    volumes:
      - minio-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server --console-address ":9001" /data

volumes:
  minio-data: